use_frameworks!

platform :ios, '8.0'

target 'XWNetwork_Example' do
  pod 'XWNetwork', :path => '../'

  target 'XWNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
